spring.application.name=Agroptima
spring.datasource.url=jdbc:postgresql://localhost:5432/agroptima
spring.datasource.username=postgres
spring.datasource.password=harentsoa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.store-type=none