spring.application.name=Agroptima
spring.datasource.url=jdbc:postgresql://localhost:5432/nom_de_ta_db
spring.datasource.username=ton_utilisateur
spring.datasource.password=ton_mot_de_passe
spring.datasource.driver-class-name=org.postgresql.Driver